<?php

/**
 * @file
 * Contains pilihan_sekolah.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pilihan_sekolah_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pilihan_sekolah module.
    case 'help.page.pilihan_sekolah':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Daftar pilihan sekolah') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_page_attachments().
 */
function pilihan_sekolah_page_attachments(&$page) {
  $pilihan_sekolah = \Drupal::routeMatch()->getParameter('pilihan_sekolah');
  if($pilihan_sekolah){
    $page['#attached']['library'][] = 'pilihan_sekolah/pilihan_sekolah';
  }
}